spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
#            redirect-uri: https://3354-121-162-236-138.ngrok-free.app/login/oauth2/code/google
            scope: profile, email
  redis:
    host: localhost
    port: 6379
jwt:
  access-token-expiration-minutes: 3600000
  oauth-access-token-expiration-minutes: 3600000
  refresh-token-expiration-minutes: 14400000

logging:
  pattern:
    console: "%white([%d{yyyy-MM-dd HH:mm:ss}]) %yellow([%thread]) %highlight([%-5level]) %white([%-35logger{35}]) %white(%msg  %n)"
  level:
#    root: DEBUG
#    jpa: DEBUG
    org:
      springframework:
        security: DEBUG
#        orm:
#          jpa: DEBUG

file:
  dir : "/images"
